spring:
  application:
    name: "Items-Service"
  cloud:
    config:
      uri:
        - http://localhost:8888
      server:
          bootstrap: false

server:
  port: 8081

# swagger-ui.html for GUI

