spring:
  application:
    name: "Employee-Service"
  cloud:
    config:
      uri:
        - http://localhost:8888
      server:
        bootstrap: false
  data:
    mongodb:
      host: localhost
      port: 27018
      datebase: "test"

server:
  port: 8083

# swagger-ui.html for GUI
