server:
  port: 8082

spring:
  application:
    name: "Sales-Service"
#  redis:
#    host: 192.168.86.242
#    port: 6380
  data:
    mongodb:
      host: localhost
      port: 27018
      datebase: "sales"
  cache:
    redis:
      time-to-live: 60000